### ISSUE TITLE
Texture flipping

### ISSUE THREAD

**Issue by ypiadyk** [BennyQBD/3DGameEngine#18]
Hello, Benny.
Not a serious problem but it's the second time (first time it was in Intro to Modern OpenGL series) I see textures rendered upside down. I guess it's because image loaders use coordinate systems with Y-axis pointing down while OpenGL uses up direction for Y texture coordinates. Do you know some easy and efficient way of flipping the image (more interested in c++ version) before we use it as the texture? I know that it can be easily fixed by reassigning texture coordinates but it would be better to stick to general convention. I can think about the most dummy for-loop over all pixels.
Thanks.

**Comment by zeyorama** [comment]
The simplest way is to turn your image upsidedown with GIMP or what ever your favourite Image Manipulation program is.
In Fragment shader, it is unnecessary computation and doing it after loading the image would increase scene loading time, but if you want, you can look into the SDL_image API, there is definitly a function for this.

**Comment by BennyQBD** [comment]
In your model loader, do 1.0 - y coordinate on all loaded texture coordinates. It's an easy fix and it only needs to be done once.

**Comment by ypiadyk** [comment]
Nice idea of fixing the mesh loader. I should have guessed. Thanks!
