### ISSUE TITLE
sampling.glh missing

### ISSUE THREAD

**Issue by Sinius15** [BennyQBD/3DGameEngine#21]
There are two files where `sampling.glh` is included. But this file does not exist.
The first call is in [lightingMain.fsh on line 1](https://github.com/BennyQBD/3DGameEngine/blob/master/res/shaders/lightingMain.fsh#L1) and the second one is in [forward-ambient.fs on line 2](https://github.com/BennyQBD/3DGameEngine/blob/master/res/shaders/forward-ambient.fs#L2). Am i the only one with this problem? Or is there actually a file missing?

Thanks in advance!

**Comment by nekdozjam** [comment]
It is missing, looks like Benny was updating java version of the engine and forgot to include it. You can copy it from C++ version here: https://github.com/BennyQBD/3DEngineCpp/tree/master/res/shaders

**Comment by BennyQBD** [comment]
Sorry; I forgot that when you add files to a project in IntelliJ, it doesn't automatically add it to your "integrated" git repository, for reasons which are beyond me.

I've gone in and added the missing files. I'd appreciate it if you could check and make sure I've got everything.

**Comment by agausmann** [comment]
There is an option in IntelliJ whether to automatically add files to the Git workspace when you create it. It asks you by default, but you must have checked an option telling it not to ask you.

**Comment by Sinius15** [comment]
Thank you very much! It is working perfect now.
