### ISSUE TITLE
Unneeded re-declaration of lights

### ISSUE THREAD

**Issue by agausmann** [BennyQBD/3DGameEngine#23]
Whilst making my own game engine, I realized that GLSL has built-in functions for spot/point lights - it even does some calculations for you, which you can access with derived states. I've been following [this tutorial](http://www.opengl.org/sdk/docs/tutorials/ClockworkCoders/lighting.php) which shows how to implement the Phong reflection model using those functions. I'm not sure how much it may mean for performance, but I don't see a reason why you have to make your own uniforms for those lights.

EDIT: On a side note, GLSL also has structs for materials (which closely mirror the wavefront .mtl file format :3). The only uniforms you'd need to declare on your own are the map samplers.

EDITEDIT: Tonight (in about 8 hours) I'll be committing an example of Phong reflection using those structs and a .mtl loader to my [3D engine repository](http://github.com/EinsteinTCG/Einstein3DEngine)

**Comment by BennyQBD** [comment]
Those are no longer part of modern OpenGL. If you look at the most recent OpenGL spec ( http://www.opengl.org/sdk/docs/man/ ), you'll see they no longer exist.

**Comment by hhanesand** [comment]
Close the issue?
