### ISSUE TITLE
Pointlights

### ISSUE THREAD

**Issue by erikverstegen** [BennyQBD/3DGameEngine#3]
I can't get the pointlights to work on the plane mesh, it works just fine with the pyramid mesh, could anyone help me out?

Here are the files for my project:
http://ikbenerik.nl/Engine.rar

**Comment by BennyQBD** [comment]
Could you please specify the following:
-What, specifically, is occurring? (i.e. What pointlights are currently doing to the plane mesh)
-What, specifically, did you expect to happen instead? (i.e. What are pointlights doing to the pyramid that they aren't doing to the plane)
-A detailed step by step process to reproduce the issue

Thanks!

**Comment by erikverstegen** [comment]
- I can't see the pointlights at all on the plane while I can see them perfectly on the pyramid mesh
- I expect to see the pointlights apply their light to the plane (which they don't right now)
- When you uncomment the first vertex and int array (the pyramid mesh) and comment the second vertex and int array (the plane mesh) you'll see the pointlights, but when you comment the pyramid mesh again and uncomment the plane mesh you can't see the pointlights.

**Comment by ghost** [comment]
I had the same problem.
You should try to:
1. try to calc the normals by hand

**Comment by erikverstegen** [comment]
Well, I thought it had something to do with the normals, so I downloaded Benny's code and looked at the calculated normals (by printing it using .toString()) which matched up with my normals. I don't think it has something to do with that.

**Comment by ghost** [comment]
ups..
1. it fixed it for me to turn of cull facing.

In the end this was the Problem and solution:
the calc normals method from benny adds all normals on one vertex just together. But if you do that on a plane you just end up with a 0- Vector -> no direction is up -> no light at all is reflected.

To solve this problem I implemented a check if the angle between the two normals is too big.
If it is i add a new Vertex vith ist own normal and change the index of the triangle.

I have re-written bennys method but I have not tested it jet.

Hope I could help.

**Comment by ghost** [comment]
Is the Plane just dark or is it bright but not light by the pointlight?

**Comment by erikverstegen** [comment]
It's dark, but I can't see the pointlight on it.

**Comment by ghost** [comment]
in wich class do you test it? i just downloaded the engine...

**Comment by ghost** [comment]
and its not the source code. You uploaded the compiled files...

**Comment by erikverstegen** [comment]
How about this one? http://ikbenerik.nl/Engine2.rar
I tested it in the Mesh class.

**Comment by ghost** [comment]
sorry i cannot find any mistake in your code at the moment.
I will look at it later again. :)

**Comment by BennyQBD** [comment]
Here's something that's stood out to me:
In your phong vertex shader, you're calculating the worldPosition from the vertex normal rather than the vertex position. I don't know if that's your issue, but it probably isn't what you intended to do.

**Comment by erikverstegen** [comment]
Thanks Benny, that actually fixed it!

**Comment by BennyQBD** [comment]
In that case, issue closed :)
