### ISSUE TITLE
Mesh Rendering

### ISSUE THREAD

**Issue by ClassicRockFan** [BennyQBD/3DGameEngine#32]
On some meshes, on only some triangles, the texture coordinates don't seem to stick.  I'm doing the Wolf. 3D Clone now with a "finished" version of the engine.  I have replaced all of the rendering code with Benny's and something still isn't right.  You'll see a screenshot also detailing my problem.  Thanks guys for your help!  

EDIT:  The door is not the only thing I've had occasional problems with but is an example that I know should work.

EDIT2: Tested it with a mesh exported from blender to the same result.

![capture](https://cloud.githubusercontent.com/assets/9539803/7971177/e3d28e0a-0a10-11e5-90f3-887f655bd920.PNG)
![capture2](https://cloud.githubusercontent.com/assets/9539803/7971178/e3d36186-0a10-11e5-8846-692b4525220a.PNG)

**Comment by ClassicRockFan** [comment]
Okay, so I've decided that I'm being extremely stupid somewhere after doing the additional graphics stuff (normal mapping, parallax mapping, etc.) so I'm starting the series over again, I am keeping the quaternion stuff though because that was a pain in the arse to make.  If anyone has any ideas for what I might have done wrong, I'm all ears.

**Comment by ClassicRockFan** [comment]
So I've narrowed it down to the parallax mapping.  Going to go through the video again soon.

**Comment by CezaryChodun** [comment]
I think it might be problem with normals... If it is you should try to select this wrong displayed faces and select "flip direction" in UVs section(on the left).

**Comment by ClassicRockFan** [comment]
It's not an issue with the normals.  It was something to do with how I was calculating one of my matrices or something with the tangents and bi tangents.

**Comment by CezaryChodun** [comment]
... That is weird. Do you think it is something wrong with your Quaternion class? If it is, you might try vecmath library for test. However Quaternion class works fine for me... When I was doing this series. I had a problem with mesh texture map, and I have to do mesh loading for my self... But in this case I'm not sure if it is a problem...
[vecmath-kopia.jar.zip](https://github.com/BennyQBD/3DGameEngine/files/402343/vecmath-kopia.jar.zip)
