### ISSUE TITLE
Fix Y-axes camera

### ISSUE THREAD

**Issue by geakstr** [BennyQBD/3DGameEngine#4]
Hello, Benny! Many thanks for the your tutorials.

How to fix camera rotation on the Y axis? This is artefact, when up or down rotation.

_Before rotate_
![before](https://f.cloud.github.com/assets/1496368/2058776/6a284e6c-8b83-11e3-95a9-7342c5fcea8c.png)
_After rotate_
![3d engine 2014-02-02 00-56-53](https://f.cloud.github.com/assets/1496368/2058778/7ed59590-8b83-11e3-8f30-74c98dd99345.png)

I think this is `Camera.rotateX(float angle)` method. I changed
`forward = forward.rotate(angle, Haxis).normalized();`
to
`forward = forward.rotate(angle, new Vector3f(1, 0, 0)).normalized();`

but this is only slightly reduced the problem. I would be grateful for help.

**Comment by BennyQBD** [comment]
I think you may have an error in your rotate calculation, as I can't seem to reproduce the error.

Could you provide a step by step explanation of how to reproduce the problem?

**Comment by geakstr** [comment]
I double checking my code and… yes your are right — this is my fail. In Vector3f.cross method I made a mistake. Thank you :)

**Comment by geakstr** [comment]
Hello again. I found new problem with camera on Y axis :-) This in your video too (at 6 min. 48 sec.) and your named it as «flash affect» http://youtu.be/ShheuoQpJR4?t=6m48s How can I fix this?

**Comment by BennyQBD** [comment]
That isn't a bug; as you can probably tell from me explicitly mentioning it in a video, it's an intended effect of using a simpler camera system for the time being. I'll show how to fix it when we create a more advanced camera system.

In the meantime, you may be interested in my GDX project's camera class, which does implement a "true" rotation system: https://github.com/BennyQBD/GDX/tree/master/GDX

**Comment by geakstr** [comment]
Ok, i successfully patch my camera with your GDX camera code :-)
